openapi: 3.0.1
info:
  title: Base
  version: 0.1.0
servers:
- url: "{server}:{port}/base"
  variables:
    server:
      default: http://localhost
    port:
      default: pseudoPort
paths:
  /welcome:
    get:
      operationId: getWelcome
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
